const STORAGE_DATA = {
  config: {
    // background
    cardStart: "../images/question/index-bg.png",
    cardCloud: "../images/question/prepare-bg.png",
    cardQuestion: "../images/question/question-bg.png",
    crystalBall: "../images/question/crystal-ball.png",
    questionArea: "../images/question/question-scroll.png",
    // decorations
    footprint: "../images/question/footprint.png",
    catIcon: "../images/result/cat-icon.png",
    cloudLeft:"../images/question/cloud-left.png",
    cloudRight:"../images/question/cloud-right.png",
    // specific
    uploadFailedFrame: "../images/question/upload-failed-frame.png",
    loadingPic: "../images/question/loading-pic.png",
    hourGlassIcon: "../images/question/hourglass-icon.png",
    // footer
    superMediaLogoLink: "../images/result/super-media-logo.png",
    armAndHammerLogo: "../images/result/arm-&-hammer-logo.png",
    // questions
    questions: [
      { id: 1, text: "領養的第一天，⋯", mbtiA: "E", mbtiB: "I" },
      { id: 2, text: "新買了一個貓跳台，{catName} ⋯", mbtiA: "S", mbtiB: "N" },
      { id: 3, text: "發現貓咪跳不上去，移動了跳台的位置，{catName} ⋯", mbtiA: "N", mbtiB: "S" },
      { id: 4, text: "初次使用貓砂，{catName}⋯", special: "premium-sensitive" },
      { id: 5, text: "此時突然飛來一張蟑螂，{catName} 會⋯", mbtiA: "S", mbtiB: "N" },
      { id: 6, text: "結果不小心打翻貓砂盆，{catName} ⋯", special: "premium-odor" },
      { id: 7, text: "當家裡廁所買了新的芳香劑，{catName} ⋯", specialA: "premium-odor", specialB: "premium-deodorize" },
      { id: 8, text: "當 {catName} 不小心被關在廁所，牠⋯", mbtiA: "T", mbtiB: "F" },
      { id: 9, text: "把 {catName} 救出來後，牠⋯", mbtiA: "T", mbtiB: "F" },
      { id: 10, text: "有一天朋友來家裡，不小心踩到 {catName}，牠⋯", mbtiA: "F", mbtiB: "T" },
      { id: 11, text: "朋友想餵貓咪吃肉泥，而 {catName}⋯" },
      { id: 12, text: "餵完肉泥後，朋友想摸貓，而 {catName}⋯", mbtiA: "P", mbtiB: "J" }
    ],
    catPersona: {
      ISTJ: "守紀乖乖喵",
      ISFJ: "體貼溫暖喵",
      INFJ: "紳士淑女喵",
      INTJ: "策略聰明喵",
      ISTP: "好奇寶寶喵",
      ISFP: "藝術恬靜喵",
      INFP: "浪漫夢幻喵",
      INTP: "思想獨立喵",
      ESTP: "勇敢冒險喵",
      ESFP: "明星交際喵",
      ENFP: "探索分享喵",
      ENTP: "創意天才喵",
      ESTJ: "管理認真喵",
      ESFJ: "溫柔貼心喵",
      ENFJ: "領導組織喵",
      ENTJ: "霸氣指揮喵",
    },
    step:{
      step1: "../images/question/進度1@2x.png",
      step2: "../images/question/進度2@2x.png",
      step3: "../images/question/進度3@2x.png",
      step4: "../images/question/進度4@2x.png",
      step5: "../images/question/進度5@2x.png",
      step6: "../images/question/進度6@2x.png",
      step7: "../images/question/進度7@2x.png",
      step8: "../images/question/進度8@2x.png",
      step9: "../images/question/進度9@2x.png",
      step10: "../images/question/進度10@2x.png",
      step11: "../images/question/進度11@2x.png",
      step12: "../images/question/進度12@2x.png"
    },
    questionImage: {
      'Q1': "../images/question/Q1@2x.png",
      'Q2': "../images/question/Q2@2x.png",
      'Q3': "../images/question/Q3@2x.png",
      'Q4': "../images/question/Q4@2x.png",
      'Q5': "../images/question/Q5@2x.png",
      'Q6': "../images/question/Q6@2x.png",
      'Q7': "../images/question/Q7@2x.png",
      'Q8': "../images/question/Q8@2x.png",
      'Q9': "../images/question/Q9@2x.png",
      'Q10': "../images/question/Q10@2x.png",
      'Q11': "../images/question/Q11@2x.png",
      'Q12': "../images/question/Q12@2x.png"
    },
    buttons:{
      startButton: "../images/question/start-button.png",
      upLoadButton: "../images/question/upload-button.png",
      nextButton: "../images/question/next-button.png",
      skipButton: "../images/question/skip-button.png",
      shareButton: "../images/result/share-button.png",
      restartButton: "../images/result/restart-button.png",
      reUploadButton: "../images/question/re-upload-button.png",
      // retakeButton:  "../images/question/retake-button.png",
      facebookButton: "../images/result/facebook-logo.png",
      // momoButton: "../images/result/momo-button.png",
      // pchomeButton: "../images/result/pchome-button.png",
      coupangButton: "../images/result/coupang-button.png",
      '1A': "../images/question/1-A@2x.png",
      '1B': "../images/question/1-B@2x.png",
      '2A': "../images/question/2-A@2x.png",
      '2B': "../images/question/2-B@2x.png",
      '3A': "../images/question/3-A@2x.png",
      '3B': "../images/question/3-B@2x.png",
      '4A': "../images/question/4-A@2x.png",
      '4B': "../images/question/4-B@2x.png",
      '5A': "../images/question/5-A@2x.png",
      '5B': "../images/question/5-B@2x.png",
      '6A': "../images/question/6-A@2x.png",
      '6B': "../images/question/6-B@2x.png",
      '7A': "../images/question/7-A@2x.png",
      '7B': "../images/question/7-B@2x.png",
      '8A': "../images/question/8-A@2x.png",
      '8B': "../images/question/8-B@2x.png",
      '9A': "../images/question/9-A@2x.png",
      '9B': "../images/question/9-B@2x.png",
      '10A': "../images/question/10-A@2x.png",
      '10B': "../images/question/10-B@2x.png",
      '11A': "../images/question/11-A@2x.png",
      '11B': "../images/question/11-B@2x.png",
      '12A': "../images/question/12-A@2x.png",
      '12B': "../images/question/12-B@2x.png"
    },
    result: {
      dashedDivider: "../images/result/dashed-divider.png",
      outcomeHint: "../images/result/outcome-hint.png",
      shareCatPersonaCTA: "../images/result/share-cat-persona.png",
      // Title
      lotteryRuleTitle: "../images/result/lottery-rule-title.png",
      channelTitle: "../images/result/channel-title.png",
      followArmAndHammerTitle: "../images/result/follow-arm-n-hammer.png",
      upload:{
        ISTJ: "../images/result/上傳貓咪照片款1@2x.png",
        ISFJ: "../images/result/上傳貓咪照片款2@2x.png",
        INFJ: "../images/result/上傳貓咪照片款3@2x.png",
        INTJ: "../images/result/上傳貓咪照片款4@2x.png",
        ISTP: "../images/result/上傳貓咪照片款5@2x.png",
        ISFP: "../images/result/上傳貓咪照片款6@2x.png",
        INFP: "../images/result/上傳貓咪照片款7@2x.png",
        INTP: "../images/result/上傳貓咪照片款8@2x.png",
        ESTP: "../images/result/上傳貓咪照片款9@2x.png",
        ESFP: "../images/result/上傳貓咪照片款10@2x.png",
        ENFP: "../images/result/上傳貓咪照片款11@2x.png",
        ENTP: "../images/result/上傳貓咪照片款12@2x.png",
        ESTJ: "../images/result/上傳貓咪照片款13@2x.png",
        ESFJ: "../images/result/上傳貓咪照片款14@2x.png",
        ENFJ: "../images/result/上傳貓咪照片款15@2x.png",
        ENTJ: "../images/result/上傳貓咪照片款16@2x.png",
      },
      noUpload:{
        ISTJ: "../images/result/不上傳款1@2x.png",
        ISFJ: "../images/result/不上傳款2@2x.png",
        INFJ: "../images/result/不上傳款3@2x.png",
        INTJ: "../images/result/不上傳款4@2x.png",
        ISTP: "../images/result/不上傳款5@2x.png",
        ISFP: "../images/result/不上傳款6@2x.png",
        INFP: "../images/result/不上傳款7@2x.png",
        INTP: "../images/result/不上傳款8@2x.png",
        ESTP: "../images/result/不上傳款9@2x.png",
        ESFP: "../images/result/不上傳款10@2x.png",
        ENFP: "../images/result/不上傳款11@2x.png",
        ENTP: "../images/result/不上傳款12@2x.png",
        ESTJ: "../images/result/不上傳款13@2x.png",
        ESFJ: "../images/result/不上傳款14@2x.png",
        ENFJ: "../images/result/不上傳款15@2x.png",
        ENTJ: "../images/result/不上傳款16@2x.png",
      }
    },
    litter: {
      'premium-sensitive': "../images/result/sensitive-litter.png",
      'premium-odor': "../images/result/odor-litter.png",
      'premium-deodorize': "../images/result/deodorize-litter.png"
    },
    links:{
      MOMO:"https://www.momoshop.com.tw/category/DgrpCategory.jsp?d_code=4700100067&p_orderType=6&showType=chessboardType&attr=%7B%22%26%2337325%3B%26%2337327%3B%22%3A%5B%226kg%26%23126%3B10kg%22%5D%7D&attrNo=%7B%22%26%2337325%3B%26%2337327%3B%22%3A%5B%22A0012G0003C0002%22%5D%7D&mAttL=%5B%22%26%2337325%3B%26%2337327%3B%22%5D",
      PCHOME:"https://24h.pchome.com.tw/store/DEAKWF",
      COUPANG:"https://www.tw.coupang.com/products/ARM%26HAMMER-%E9%A0%82%E7%B4%9A%E9%99%A4%E8%87%AD%E8%B2%93%E7%A0%82-452665263734784?vendorItemId=458122208460802&sourceType=SDP_ALSO_VIEWED&searchId=807dbfbd6a43419f929fd52299d5dc94",
      SUPERMEDIA:"https://www.supermedia.cool/"
    },
    litterLinks: {
      'premium-sensitive': 'https://reurl.cc/VMOnOZ',
      'premium-odor': 'https://reurl.cc/5dWXnv',
      'premium-deodorize': 'https://reurl.cc/qvAaey'
    }
  },
};

export default STORAGE_DATA;
