const STORAGE_DATA = {
    config: {
      background: "/test-dom/images/backgrounds/desktop-background.png",
      // background
      cardStart: "/test-dom/images/backgrounds/index-bg.png",
      cardCloud: "/test-dom/images/backgrounds/prepare-bg.png",
      cardQuestion: "/test-dom/images/backgrounds/question-bg.png",
      // small-bg
      crystalBall: "/test-dom/images/crystal-ball.png",
      questionArea: "/test-dom/images/backgrounds/question-scroll.png",
      // decorations
      footprint: "/test-dom/images/footprint.png",
      catIcon: "/test-dom/images/decorations/cat-icon.png",
      cloudLeft:"/test-dom/images/decorations/cloud-left.png",
      cloudRight:"/test-dom/images/decorations/cloud-right.png",
      // specific
      uploadFailedFrame: "/test-dom/images/backgrounds/upload-failed-frame.png",
      loadingPic: "/test-dom/images/loading-pic.png",
      hourGlassIcon: "/test-dom/images/decorations/hourglass-icon.png",
      // footer
      superMediaLogoLink: "/test-dom/images/footer/super-media-logo.png",
      armAndHammerLogo: "/test-dom/images/footer/arm-&-hammer-logo.png",
      // questions
      questions: [
        { id: 1, text: "{catName}\n來家裡的第一天⋯", mbtiA: "E", mbtiB: "I" },
        { id: 2, text: "新買了一個貓跳台⋯", mbtiA: "S", mbtiB: "N" },
        { id: 3, text: "發現 {catName} 跳不上去，移動了跳台的位置", mbtiA: "N", mbtiB: "S" },
        { id: 4, text: "初次使用貓砂⋯", specialA: "premium-sensitive" },
        { id: 5, text: "此時突然飛來一隻蝴蝶⋯", mbtiA: "S", mbtiB: "N" },
        { id: 6, text: "結果不小心打翻貓砂盆⋯", specialA: "premium-deodorize" },
        { id: 7, text: "當家裡廁所買了\n新的芳香劑⋯", specialA: "premium-deodorize", specialB: "premium-odor" },
        { id: 8, text: "當 {catName} 不小心被關在廁所，牠會⋯", mbtiA: "T", mbtiB: "F" },
        { id: 9, text: "你把 {catName} 救出來後\n牠⋯", mbtiA: "T", mbtiB: "F" },
        { id: 10, text: "有一天朋友來家裡，\n不小心踩到 {catName}，\n牠會⋯", mbtiA: "F", mbtiB: "T" },
        { id: 11, text: "朋友想餵 {catName}\n吃肉泥⋯" },
        { id: 12, text: "餵完肉泥後，朋友想摸貓，牠會⋯", mbtiA: "P", mbtiB: "J" }
      ],
      catPersona: {
        ISTJ: "守紀乖乖喵",
        ISFJ: "體貼溫暖喵",
        INFJ: "紳士淑女喵",
        INTJ: "策略聰明喵",
        ISTP: "好奇寶寶喵",
        ISFP: "藝術恬靜喵",
        INFP: "浪漫夢幻喵",
        INTP: "思想獨立喵",
        ESTP: "勇敢冒險喵",
        ESFP: "明星交際喵",
        ENFP: "探索分享喵",
        ENTP: "創意天才喵",
        ESTJ: "管理認真喵",
        ESFJ: "溫柔貼心喵",
        ENFJ: "領導組織喵",
        ENTJ: "霸氣指揮喵",
      },
      step:{
        step1: "/test-dom/images/question/process_01.png",
        step2: "/test-dom/images/question/process_02.png",
        step3: "/test-dom/images/question/process_03.png",
        step4: "/test-dom/images/question/process_04.png",
        step5: "/test-dom/images/question/process_05.png",
        step6: "/test-dom/images/question/process_06.png",
        step7: "/test-dom/images/question/process_07.png",
        step8: "/test-dom/images/question/process_08.png",
        step9: "/test-dom/images/question/process_09.png",
        step10: "/test-dom/images/question/process_10.png",
        step11: "/test-dom/images/question/process_11.png",
        step12: "/test-dom/images/question/process_12.png"
      },
      questionImage: {
        'Q1': "/test-dom/images/question/Q1.png",
        'Q2': "/test-dom/images/question/Q2.png",
        'Q3': "/test-dom/images/question/Q3.png",
        'Q4': "/test-dom/images/question/Q4.png",
        'Q5': "/test-dom/images/question/Q5.png",
        'Q6': "/test-dom/images/question/Q6.png",
        'Q7': "/test-dom/images/question/Q7.png",
        'Q8': "/test-dom/images/question/Q8.png",
        'Q9': "/test-dom/images/question/Q9.png",
        'Q10': "/test-dom/images/question/Q10.png",
        'Q11': "/test-dom/images/question/Q11.png",
        'Q12': "/test-dom/images/question/Q12.png"
      },
      buttons:{
        startButton: "/test-dom/images/buttons/start-button.png",
        uploadButton: "/test-dom/images/buttons/upload-button.png",
        nextButton: "/test-dom/images/buttons/next-button.png",
        skipButton: "/test-dom/images/buttons/skip-button.png",
        shareButton: "/test-dom/images/buttons/share-button.png",
        restartButton: "/test-dom/images/buttons/restart-button.png",
        reUploadButton: "/test-dom/images/buttons/re-upload-button.png",
        // retakeButton:  "/test-dom/images/buttons/retake-button.png",
        facebookButton: "/test-dom/images/buttons/facebook-logo.png",
        // momoButton: "/test-dom/images/buttons/momo-button.png",
        // pchomeButton: "/test-dom/images/buttons/pchome-button.png",
        coupangButton: "/test-dom/images/buttons/coupang-button.png",
        cancelButton: "/test-dom/images/buttons/cancel-button.png",
        confirmButton: "/test-dom/images/buttons/confirm-button.png",
        '1A': "/test-dom/images/question/1-A.png",
        '1B': "/test-dom/images/question/1-B.png",
        '2A': "/test-dom/images/question/2-A.png",
        '2B': "/test-dom/images/question/2-B.png",
        '3A': "/test-dom/images/question/3-A.png",
        '3B': "/test-dom/images/question/3-B.png",
        '4A': "/test-dom/images/question/4-A.png",
        '4B': "/test-dom/images/question/4-B.png",
        '5A': "/test-dom/images/question/5-A.png",
        '5B': "/test-dom/images/question/5-B.png",
        '6A': "/test-dom/images/question/6-A.png",
        '6B': "/test-dom/images/question/6-B.png",
        '7A': "/test-dom/images/question/7-A.png",
        '7B': "/test-dom/images/question/7-B.png",
        '8A': "/test-dom/images/question/8-A.png",
        '8B': "/test-dom/images/question/8-B.png",
        '9A': "/test-dom/images/question/9-A.png",
        '9B': "/test-dom/images/question/9-B.png",
        '10A': "/test-dom/images/question/10-A.png",
        '10B': "/test-dom/images/question/10-B.png",
        '11A': "/test-dom/images/question/11-A.png",
        '11B': "/test-dom/images/question/11-B.png",
        '12A': "/test-dom/images/question/12-A.png",
        '12B': "/test-dom/images/question/12-B.png"
      },
      result: {
        dashedDivider: "/test-dom/images/dashed-divider.png",
        outcomeHint: "/test-dom/images/outcome-hint.png",
        shareCatPersonaCTA: "/test-dom/images/CTA-share-cat-persona.png",
        // Title
        lotteryRuleTitle: "/test-dom/images/result/title-lottery-rule.png",
        channelTitle: "/test-dom/images/result/title-channel.png",
        followArmAndHammerTitle: "/test-dom/images/result/title-follow-arm-n-hammer.png",
        upload:{
          ISTJ: "/test-dom/images/result/uploaded_outcome_01_ISTJ.png",
          ISFJ: "/test-dom/images/result/uploaded_outcome_02_ISFJ.png",
          INFJ: "/test-dom/images/result/uploaded_outcome_03_INFJ.png",
          INTJ: "/test-dom/images/result/uploaded_outcome_04_INTJ.png",
          ISTP: "/test-dom/images/result/uploaded_outcome_05_ISTP.png",
          ISFP: "/test-dom/images/result/uploaded_outcome_06_ISFP.png",
          INFP: "/test-dom/images/result/uploaded_outcome_07_INFP.png",
          INTP: "/test-dom/images/result/uploaded_outcome_08_INTP.png",
          ESTP: "/test-dom/images/result/uploaded_outcome_09_ESTP.png",
          ESFP: "/test-dom/images/result/uploaded_outcome_10_ESFP.png",
          ENFP: "/test-dom/images/result/uploaded_outcome_11_ENFP.png",
          ENTP: "/test-dom/images/result/uploaded_outcome_12_ENTP.png",
          ESTJ: "/test-dom/images/result/uploaded_outcome_13_ESTJ.png",
          ESFJ: "/test-dom/images/result/uploaded_outcome_14_ESFJ.png",
          ENFJ: "/test-dom/images/result/uploaded_outcome_15_ENFJ.png",
          ENTJ: "/test-dom/images/result/uploaded_outcome_16_ENTJ.png",
        },
        noUpload:{
          ISTJ: "/test-dom/images/result/not_uploaded_outcome_01_ISTJ.png",
          ISFJ: "/test-dom/images/result/not_uploaded_outcome_02_ISFJ.png",
          INFJ: "/test-dom/images/result/not_uploaded_outcome_03_INFJ.png",
          INTJ: "/test-dom/images/result/not_uploaded_outcome_04_INTJ.png",
          ISTP: "/test-dom/images/result/not_uploaded_outcome_05_ISTP.png",
          ISFP: "/test-dom/images/result/not_uploaded_outcome_06_ISFP.png",
          INFP: "/test-dom/images/result/not_uploaded_outcome_07_INFP.png",
          INTP: "/test-dom/images/result/not_uploaded_outcome_08_INTP.png",
          ESTP: "/test-dom/images/result/not_uploaded_outcome_09_ESTP.png",
          ESFP: "/test-dom/images/result/not_uploaded_outcome_10_ESFP.png",
          ENFP: "/test-dom/images/result/not_uploaded_outcome_11_ENFP.png",
          ENTP: "/test-dom/images/result/not_uploaded_outcome_12_ENTP.png",
          ESTJ: "/test-dom/images/result/not_uploaded_outcome_13_ESTJ.png",
          ESFJ: "/test-dom/images/result/not_uploaded_outcome_14_ESFJ.png",
          ENFJ: "/test-dom/images/result/not_uploaded_outcome_15_ENFJ.png",
          ENTJ: "/test-dom/images/result/not_uploaded_outcome_16_ENTJ.png"
        }
      },
      litter: {
        'premium-sensitive': "/test-dom/images/result/litter-sensitive.png",
        'premium-odor': "/test-dom/images/result/litter-odor.png",
        'premium-deodorize': "/test-dom/images/result/litter-deodorize.png"
      },
      links:{
        MOMO:"https://www.momoshop.com.tw/category/DgrpCategory.jsp?d_code=4700100067&p_orderType=6&showType=chessboardType&attr=%7B%22%26%2337325%3B%26%2337327%3B%22%3A%5B%226kg%26%23126%3B10kg%22%5D%7D&attrNo=%7B%22%26%2337325%3B%26%2337327%3B%22%3A%5B%22A0012G0003C0002%22%5D%7D&mAttL=%5B%22%26%2337325%3B%26%2337327%3B%22%5D",
        PCHOME:"https://24h.pchome.com.tw/store/DEAKWF",
        COUPANG:"https://www.tw.coupang.com/products/ARM%26HAMMER-%E9%A0%82%E7%B4%9A%E9%99%A4%E8%87%AD%E8%B2%93%E7%A0%82-452665263734784?vendorItemId=458122208460802&sourceType=SDP_ALSO_VIEWED&searchId=807dbfbd6a43419f929fd52299d5dc94",
        SUPERMEDIA:"https://www.supermedia.cool/",
        INSTAGRAM:"https://www.instagram.com/ttshow.tw/"
      },
      litterLinks: {
        'premium-sensitive': 'https://reurl.cc/VMOnOZ',
        'premium-odor': 'https://reurl.cc/5dWXnv',
        'premium-deodorize': 'https://reurl.cc/qvAaey'
      }
    },
  };
  
  export default STORAGE_DATA;